// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default'];
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default'];
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default'];
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default'];
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default'];
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default'];
    NButton: typeof import('naive-ui')['NButton'];
    NH2: typeof import('naive-ui')['NH2'];
    NIcon: typeof import('naive-ui')['NIcon'];
    NLayout: typeof import('naive-ui')['NLayout'];
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader'];
    NLayoutSider: typeof import('naive-ui')['NLayoutSider'];
    NSwitch: typeof import('naive-ui')['NSwitch'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    ThemeSwitch: typeof import('./src/components/ThemeSwitch.vue')['default'];
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default'];
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default'];
  }
}
